
set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)

vcpkg_find_cuda(OUT_CUDA_TOOLKIT_ROOT CUDA_TOOLKIT_ROOT OUT_CUDA_VERSION CUDA_VERSION)
message(STATUS "Found CUDA '${CUDA_VERSION}': '${CUDA_TOOLKIT_ROOT}'")

list(APPEND CMAKE_MODULE_PATH "${CURRENT_INSTALLED_DIR}/share/cudnn")
find_package(CUDNN REQUIRED)

vcpkg_install_copyright(FILE_LIST "${VCPKG_ROOT_DIR}/LICENSE.txt")
